## The following functions cache the inverse of matrix so as to save computation
## time when the same matrices are repeated

## makeCacheMatrix function takes a matrix as input
## it basically forms four objects(functions) namely, 
## set();get();setmatrix();getmatrix()
## set assigns the inout matrix to variable 'x'
## get returns the matrix stored in variable 'x'
## setmatrix stores the inverse in a variable 'm'
## getmatrix returns the inverse of the input matrix, which is inturn calculated
##    by the cacheSolve()

makeCacheMatrix <- function(x = matrix()) {
  m<-NULL
  set<-function(y = matrix()){
    x<<-y
    m<<-NULL
  }
  get<-function() x
  setmatrix<-function(solve) m<<- solve
  getmatrix<-function() m
  list(set=set, get=get,
       setmatrix=setmatrix,
       getmatrix=getmatrix)
}


## the cacheSolve functions works in two phases; 
## 1. it takes in the object(list of functions generated by makeCacheMatrix())
## 2. it checkes if the matrix inverse has already been calculated by calling 
##    the getmatrix()
## if the inverse existed for the same matrix the it just returns the already 
## calculated inverse, otherwise it calculates and caches the inverse using
## solve() and setmatrix() respectively

cacheSolve <- function(x, ...) {
  m<-x$getmatrix()
  if(!is.null(m)){
    message("getting cached data")
    return(m)
  }
  else{
    matrix<-x$get()
    m<-solve(matrix, ...)
    x$setmatrix(m)
    m
  }
}
